version: "3.7"

services: 

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=MyFlaskApp
    expose: 
      - 8080
  
  django:
    build: ./django_app
    container_name: django_app
    restart: always
    environment: 
      - APP_NAME=DjangoApp
    expose: 
      - 8010

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"