version: "3.7"

services: 

  cws:
    build: ./custom_ws
    container_name: cws
    restart: always
    environment: 
      - APP_NAME=CustomWebServer
    expose: 
      - 8001

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=MyFlaskApp
    expose: 
      - 8002
  
  django:
    build: ./django_app
    container_name: django_app
    restart: always
    environment: 
      - APP_NAME=DjangoApp
    expose: 
      - 8003

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"